### ISSUE TITLE
Type Assertion due to invalid cast

### ISSUE THREAD

**Issue by kumarak** [trailofbits/vast#171]
I see type assertion due to invalid cast from NamedType to FunctionType. It happens because typedef is getting lowered as NamedType. The issue can be reproduce with the code:

```
typedef int function_type(int a, int b);
function_type *p[2];
int test_func(void) {
  return p[1](15, 20);
}
```
https://github.com/trailofbits/vast/blob/master/lib/vast/Dialect/HighLevel/HighLevelTypes.cpp#L18
https://github.com/trailofbits/vast/blob/master/lib/vast/Dialect/HighLevel/HighLevelTypes.cpp#L23

**Comment by lkorenc** [comment]
`NamedType` is no longer present, will need to retest.
