### ISSUE TITLE
Function redeclaration error

### ISSUE THREAD

**Issue by xlauko** [trailofbits/vast#265]
Deal with compilation of:

```
void abort();
void abort();
int main() {}
```

respectively:

```
void abort();
void abort() {}
int main() {}
```

This is minimal example of #253

**Comment by xlauko** [comment]
The problem is that SymbolTable maps from `clang::FuncDecl`, which are different tokens for `abort` definitions. Therefore the function is not deduplicated.

**Comment by pgoodman** [comment]
@xlauko don't forget

```c
typedef void (abort_t)();
abort_t abort;
```
