### ISSUE TITLE
How to generate programs that use the dialets on the official mlir website

### ISSUE THREAD

**Issue by CelestineSmith** [trailofbits/vast#271]
When I executed ```vast-cc -ccopts -xc --from-source csmith_vast.c```, it translated the C program into a program that uses ```hl``` dialect. Could anyone tell me how to compile C programs through ```Vast``` into programs that use those dialets on the official mlir website, e.g. ```llvm``` dialect? (https://mlir.llvm.org/docs/Dialects/)
The content of ```csmith_vast.c``` :
```console
#define NO_LONGLONG

#include "csmith.h"


static long __undefined;

static int16_t  func_1(void);

static int16_t  func_1(void)
{ /* block id: 0 */
    int32_t l_2 = (-1);
    int16_t l_3 = 0x5B40;
    int32_t l_4 = 1;
    int8_t l_5 = 0x9A;
    l_2 &= 0x5052061F;
    l_4 = l_3;
    l_5 = 0;
    l_4 ^= 0x7B8F5F49;
    return l_5;
}


int main (int argc, char* argv[])
{
    int print_hash_value = 0;
    if (argc == 2 && strcmp(argv[1], "1") == 0) print_hash_value = 1;
    platform_main_begin();
    crc32_gentab();
    func_1();
    platform_main_end(crc32_context ^ 0xFFFFFFFFUL, print_hash_value);
    return 0;
}
```

**Comment by lkorenc** [comment]
Hi,

so first of all sorry on this not being properly documented, it is on my todo list.

In the upcoming days (by Monday I hope) we should merge code that allows `vast-front` to simply work as `clang`, e.g. all that will need to be done is `vast-front -c -S -vast-emit-llvm source.c`. (This will produce an LLVM IR module - not mlir module - I can add an option to emit llvm dialect as well if that is of interest to you).

What works now is invoking `vast-opt` manually with a correct chain of transformation passes.
Something along
```bash
vast-cc ... compile to hl ... | vast-opt --vast-hl-lower-types
                                         --vast-hl-to-ll-cf
                                         --vast-hl-structs-to-llvm
                                         --vast-hl-to-ll-vars
                                         --vast-irs-to-llvm
```
If you want an LLVM IR adding `--vast-dump-llvm` as the last opt will do that.

Unfortunately compared to rather strong `C -> hl` support, when going `hl -> llvm` it is much more tricky to do the `->` properly and we are still working on it. If you encounter problems and report them we can prioritise fixing them.

Looking at your example it looks like we should support it, it really depends what magic hides inside that one `include`.

Hope I helped :)

**Comment by CelestineSmith** [comment]
@lkorenc Thank you for your reply, when I executed ```vast-opt --vast-hl-lower-types --vast-hl-to-ll-cf --vast-hl-structs-to-llvm --vast-hl-to-ll-vars --vast-irs-to-llvm --vast-dump-llvm csmith_vast.mlir```, it turned out to be:
```console
csmith_vast.mlir:633:41: error: expected '"' in string literal
    %4 = hl.const #hl.str<"checksum = %X
                                        ^
```
If possible, I hope you can add the option of emit llvm dialect to the  ```vast-front``` when merging code. :）

**Comment by lkorenc** [comment]
I will investigate this (and possibly other issues that will probably arise) and let you know, but it will take a while.

**Comment by CelestineSmith** [comment]
I'm sorry to bother you, may I know when the PR with the ```-vast-emit-mlir``` support can be merged?

**Comment by lkorenc** [comment]
So you can pretty much use it now - we are having problems with some linking when LLVM is compiled into dynamic libraries, which may be fine for you.
That will however only add support for the flag - the underlying issues in your source are still on todo (I do not want to give you an estimate because I have really no idea how long it will take me).

**Comment by lkorenc** [comment]
Currently `vast-front` accepts `-vast-emit-mlir=[hl,llvm]` as options. If you desire some more "mid-level" transformation, have a look at passes `vast-opt` provides (they start with `-vast`).

If you encounter any problems or have any other questions open a new issue, I am closing this one as it was open for an older version of VAST (and therefore may no longer be relevant - feel free to re-open if you find that the same problem persists).
