### ISSUE TITLE
`vast-front` doesn't create static global variables

### ISSUE THREAD

**Issue by Jezurko** [trailofbits/vast#341]
- Seems like it doesn't go through `VisitVarDecl` at all for some reason (normal global variables do go through it)
- Fails silently - the crash occurs when we attempt to get the defining op in processing of a use of the variable
- It also isn't present in the resulting MLIR
- Minimal example:
```
static int a = 2;
int main(int argc, char *argv[]) {
    int x = a;
    return 0;
}
```

**Comment by pgoodman** [comment]
Make sure to also try having the `static int a` within the function definition, i.e. lexical != semantic decl context.

**Comment by pgoodman** [comment]
Also be sure to try:
```
static int a = 2;
int main(int argc, char *argv[]) {
  int x;
  if (argc) {
    static int a = 1;
    x = a;
  } else {
    static int a = 2;
    x = a;
  }
  return x;
}
```
