### ISSUE TITLE
[Bug]: CMakeLists's cmake_minimum_required version has to be updated

### ISSUE THREAD

**Issue by yousifBilal** [trailofbits/vast#485]
### VAST version

latest

### LLVM version

17

### Operating system

Linux, Ubuntu 22.04

### Description

BRIEF_DOCS argument for define_property became [optional in cmake 3.23](https://cmake.org/cmake/help/latest/command/define_property.html). If one would have cmake version below that this error would be thrown:<br>
CMake Error at CMakeLists.txt:252 (define_property):
  define_property not given a BRIEF_DOCS <brief-doc> argument.

### Steps to Reproduce

Have cmake version below 3.23.

**Comment by lkorenc** [comment]
Thanks for report, addressed as part of #486
