### ISSUE TITLE
Figure out re-usability of existing transformation

### ISSUE THREAD

**Issue by lkorenc** [trailofbits/vast#50]
When we transform/translate IR in vast, there are metadata we want to keep attached to operations to help us keep track of provenance. In our own passes, this is fine as we can ensure they are emitted properly. However, there is a lot of transformations that are not written by us and yet we would like to use them (such as `std -> llvm` for example).

If the external transformation works in a `1:N` fashion only, we should be able to re-use it by utilising the `Listener` class that can be registered into `Builder` (from which the rewriter should inherit).
 * I am not sure `Listener` is 100% reliable (it does not seem to be used much by the codebase)
 * We must be certain that the external transformation always creates/deletes new nodes via the API it should.

The core idea is that each newly created node will be given the attribute of its origin by the `Listener` class. This will require a possibly verbose wrapper around the external transformation, but still better than rewriting it from scratch.

In case transformation is `N:M` (from multiple instruction another bunch is created), I am not sure what to do.

**Comment by pgoodman** [comment]
Will third-party transforms preserve/propagate locations? Can you rely on fusing self-references into locations?
