### ISSUE TITLE
Add option to choose a dialect to use to coerce values when lowering to SCF.

### ISSUE THREAD

**Issue by lkorenc** [trailofbits/vast#97]
Since we need to go `i32 -> i1` there are a few options that naturally come to mind - `hl.` cast or `trunc` from standard dialect. It would be probably for the best to provide an option so users can choose - as this pass will be most likely just one step in a longer transformation pipeline.

**Comment by xlauko** [comment]
`trunc` is not correct.  What if I truncate nonzero value to zero?
